# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: dega

builds:
- id: dega-server
  dir: server
  binary: dega-server
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64

archives:
  - id: dega-server
    builds:
      - dega-server 
    name_template: "dega-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

dockers:
- dockerfile: server/Dockerfile.prod
  image_templates:
    - "factly/dega-server:{{ .Tag }}"
  use: docker
  build_flag_templates:
  - "--platform=linux/amd64"

docker_manifests:
  - 
    image_templates:
    - "factly/dega-server:{{ .Version }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
